services:
  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - dev.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
